const mongoose = require("mongoose");
const dotenv = require("dotenv");
dotenv.config();

const Product = require("../models/Product");
const User = require("../models/User");

const products = [
    // Electronics
    {
        name: "Wireless Bluetooth Headphones Pro",
        description: "Premium noise-cancelling wireless headphones with 30hr battery life, deep bass, and foldable design. Perfect for music lovers and remote workers.",
        price: 1999,
        originalPrice: 3499,
        category: "Electronics",
        brand: "SoundMax",
        stock: 50,
        featured: true,
        images: [{ public_id: "e1", url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400" }],
        tags: ["headphones", "wireless", "bluetooth"],
    },
    {
        name: "Smart LED Desk Lamp",
        description: "Touch-controlled LED desk lamp with 5 brightness levels, USB charging port, and eye-care mode.",
        price: 1299,
        originalPrice: 2199,
        category: "Electronics",
        brand: "LumiTech",
        stock: 40,
        featured: true,
        images: [{ public_id: "e2", url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400" }],
        tags: ["lamp", "desk", "led"],
    },
    {
        name: "Mechanical Gaming Keyboard RGB",
        description: "RGB backlit mechanical keyboard with blue switches, anti-ghosting and detachable USB-C cable.",
        price: 2499,
        originalPrice: 3999,
        category: "Electronics",
        brand: "KeyMaster",
        stock: 30,
        featured: true,
        images: [{ public_id: "e3", url: "https://images.unsplash.com/photo-1561112078-7d24e04c3407?w=400" }],
        tags: ["keyboard", "gaming", "mechanical"],
    },
    {
        name: "Portable Bluetooth Speaker",
        description: "360-degree surround sound speaker with 24hr battery, IPX7 waterproof rating.",
        price: 1499,
        originalPrice: 2499,
        category: "Electronics",
        brand: "SoundMax",
        stock: 60,
        featured: false,
        images: [{ public_id: "e4", url: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400" }],
        tags: ["speaker", "bluetooth", "waterproof"],
    },
    {
        name: "Wireless Gaming Mouse",
        description: "Ultra-lightweight wireless gaming mouse with 70hr battery and 16000 DPI sensor.",
        price: 1799,
        originalPrice: 2799,
        category: "Electronics",
        brand: "KeyMaster",
        stock: 45,
        featured: false,
        images: [{ public_id: "e5", url: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=400" }],
        tags: ["mouse", "gaming", "wireless"],
    },
    {
        name: "USB-C 65W Fast Charger",
        description: "GaN technology 65W fast charger compatible with laptops, phones and tablets.",
        price: 799,
        originalPrice: 1299,
        category: "Electronics",
        brand: "ChargeFast",
        stock: 100,
        featured: false,
        images: [{ public_id: "e6", url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400" }],
        tags: ["charger", "usbc", "fast charging"],
    },
    {
        name: "Smart Watch Fitness Tracker",
        description: "Health smartwatch with heart rate monitor, SpO2 sensor, GPS and 7-day battery.",
        price: 3499,
        originalPrice: 5999,
        category: "Electronics",
        brand: "FitPro",
        stock: 35,
        featured: true,
        images: [{ public_id: "e7", url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400" }],
        tags: ["smartwatch", "fitness", "health"],
    },
    {
        name: "Laptop Stand Adjustable",
        description: "Ergonomic aluminum laptop stand with 6 height levels and heat dissipation. Fits 10-16 inch laptops.",
        price: 899,
        originalPrice: 1499,
        category: "Electronics",
        brand: "DeskPro",
        stock: 70,
        featured: false,
        images: [{ public_id: "e8", url: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400" }],
        tags: ["laptop", "stand", "ergonomic"],
    },
    {
        name: "True Wireless Earbuds ANC",
        description: "Active noise cancellation earbuds with 8hr playtime, IPX4 water resistance and touch controls.",
        price: 2199,
        originalPrice: 3499,
        category: "Electronics",
        brand: "SoundMax",
        stock: 55,
        featured: true,
        images: [{ public_id: "e9", url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400" }],
        tags: ["earbuds", "wireless", "anc"],
    },
    {
        name: "4K Webcam with Microphone",
        description: "4K ultra HD webcam with built-in stereo microphone, autofocus and privacy cover.",
        price: 3999,
        originalPrice: 5999,
        category: "Electronics",
        brand: "CamPro",
        stock: 25,
        featured: false,
        images: [{ public_id: "e10", url: "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400" }],
        tags: ["webcam", "4k", "microphone"],
    },
    {
        name: "Portable SSD 1TB",
        description: "Ultra-fast portable SSD with 1050MB/s read speed, USB 3.2 Gen 2 and shock-resistant design.",
        price: 4999,
        originalPrice: 7499,
        category: "Electronics",
        brand: "SpeedDrive",
        stock: 20,
        featured: false,
        images: [{ public_id: "e11", url: "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=400" }],
        tags: ["ssd", "storage", "portable"],
    },
    {
        name: "Ring Light 18 inch",
        description: "Professional 18-inch ring light with tripod stand, phone holder and remote for content creators.",
        price: 1999,
        originalPrice: 3499,
        category: "Electronics",
        brand: "LumiTech",
        stock: 30,
        featured: false,
        images: [{ public_id: "e12", url: "https://images.unsplash.com/photo-1616628188502-0dbc98293600?w=400" }],
        tags: ["ringlight", "photography", "youtube"],
    },

    // Clothing
    {
        name: "Men's Casual Cotton T-Shirt",
        description: "Comfortable 100% cotton t-shirt. Perfect for everyday wear with relaxed fit.",
        price: 399,
        originalPrice: 699,
        category: "Clothing",
        brand: "StyleCo",
        stock: 200,
        featured: true,
        images: [{ public_id: "c1", url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400" }],
        tags: ["tshirt", "casual", "cotton"],
    },
    {
        name: "Women's Floral Summer Dress",
        description: "Lightweight floral print summer dress with A-line silhouette in breathable chiffon fabric.",
        price: 899,
        originalPrice: 1599,
        category: "Clothing",
        brand: "FashionHub",
        stock: 80,
        featured: true,
        images: [{ public_id: "c2", url: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400" }],
        tags: ["dress", "summer", "floral"],
    },
    {
        name: "Men's Slim Fit Jeans",
        description: "Premium stretch denim slim fit jeans with 5-pocket styling and modern cut.",
        price: 1299,
        originalPrice: 2199,
        category: "Clothing",
        brand: "DenimCo",
        stock: 120,
        featured: false,
        images: [{ public_id: "c3", url: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400" }],
        tags: ["jeans", "denim", "slim fit"],
    },
    {
        name: "Women's Hoodie Sweatshirt",
        description: "Super soft fleece hoodie with kangaroo pocket and adjustable drawstring.",
        price: 799,
        originalPrice: 1399,
        category: "Clothing",
        brand: "ComfortWear",
        stock: 90,
        featured: false,
        images: [{ public_id: "c4", url: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400" }],
        tags: ["hoodie", "sweatshirt", "cozy"],
    },
    {
        name: "Men's Formal Blazer",
        description: "Classic single-breasted blazer in premium wool blend. Perfect for office and formal events.",
        price: 2499,
        originalPrice: 4499,
        category: "Clothing",
        brand: "StyleCo",
        stock: 40,
        featured: true,
        images: [{ public_id: "c5", url: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400" }],
        tags: ["blazer", "formal", "office"],
    },
    {
        name: "Women's Yoga Pants",
        description: "High-waist compression yoga pants with 4-way stretch, squat-proof and moisture-wicking.",
        price: 699,
        originalPrice: 1199,
        category: "Clothing",
        brand: "FitWear",
        stock: 150,
        featured: false,
        images: [{ public_id: "c6", url: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400" }],
        tags: ["yoga", "pants", "fitness"],
    },
    {
        name: "Men's Running Shorts",
        description: "Lightweight quick-dry running shorts with liner, zippered pocket and reflective details.",
        price: 499,
        originalPrice: 899,
        category: "Clothing",
        brand: "FitWear",
        stock: 110,
        featured: false,
        images: [{ public_id: "c7", url: "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=400" }],
        tags: ["shorts", "running", "sports"],
    },
    {
        name: "Winter Puffer Jacket",
        description: "Warm puffer jacket with water-resistant shell, down fill and packable design.",
        price: 2999,
        originalPrice: 4999,
        category: "Clothing",
        brand: "WinterWear",
        stock: 45,
        featured: true,
        images: [{ public_id: "c8", url: "https://images.unsplash.com/photo-1547624643-3bf761b09502?w=400" }],
        tags: ["jacket", "winter", "puffer"],
    },
    {
        name: "Cotton Polo T-Shirt",
        description: "Classic polo shirt in premium pique cotton with ribbed collar for smart casual look.",
        price: 599,
        originalPrice: 999,
        category: "Clothing",
        brand: "StyleCo",
        stock: 160,
        featured: false,
        images: [{ public_id: "c9", url: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400" }],
        tags: ["polo", "tshirt", "smart casual"],
    },
    {
        name: "Women's Kurti Set",
        description: "Elegant printed cotton kurti with palazzo pants. Perfect for casual and semi-formal occasions.",
        price: 899,
        originalPrice: 1499,
        category: "Clothing",
        brand: "EthnicHub",
        stock: 75,
        featured: false,
        images: [{ public_id: "c10", url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400" }],
        tags: ["kurti", "ethnic", "cotton"],
    },

    // Books
    {
        name: "The Pragmatic Programmer",
        description: "A must-read for every software developer covering best practices and clean code.",
        price: 549,
        originalPrice: 799,
        category: "Books",
        brand: "Addison-Wesley",
        stock: 80,
        featured: false,
        images: [{ public_id: "b1", url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400" }],
        tags: ["programming", "developer", "coding"],
    },
    {
        name: "Atomic Habits",
        description: "James Clear's guide to building good habits and breaking bad ones. Over 10 million copies sold.",
        price: 399,
        originalPrice: 599,
        category: "Books",
        brand: "Penguin",
        stock: 120,
        featured: true,
        images: [{ public_id: "b2", url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400" }],
        tags: ["self-help", "habits", "productivity"],
    },
    {
        name: "Clean Code",
        description: "Robert C. Martin's definitive guide to writing clean and maintainable code.",
        price: 649,
        originalPrice: 899,
        category: "Books",
        brand: "Prentice Hall",
        stock: 60,
        featured: false,
        images: [{ public_id: "b3", url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400" }],
        tags: ["programming", "clean code", "software"],
    },
    {
        name: "Rich Dad Poor Dad",
        description: "Robert Kiyosaki's personal finance classic about money, investing and financial independence.",
        price: 299,
        originalPrice: 499,
        category: "Books",
        brand: "Warner Books",
        stock: 150,
        featured: false,
        images: [{ public_id: "b4", url: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400" }],
        tags: ["finance", "investing", "money"],
    },
    {
        name: "JavaScript: The Good Parts",
        description: "Douglas Crockford's essential guide to the best features of JavaScript.",
        price: 449,
        originalPrice: 699,
        category: "Books",
        brand: "O'Reilly",
        stock: 50,
        featured: false,
        images: [{ public_id: "b5", url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400" }],
        tags: ["javascript", "programming", "web"],
    },
    {
        name: "Think and Grow Rich",
        description: "Napoleon Hill's timeless classic on success, mindset and achieving your goals.",
        price: 249,
        originalPrice: 399,
        category: "Books",
        brand: "Fingerprint",
        stock: 200,
        featured: false,
        images: [{ public_id: "b6", url: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400" }],
        tags: ["success", "mindset", "motivation"],
    },

    // Home & Kitchen
    {
        name: "Stainless Steel Water Bottle 1L",
        description: "Insulated 1-litre bottle keeps drinks cold 24hrs and hot 12hrs. Leak-proof and BPA-free.",
        price: 699,
        originalPrice: 1199,
        category: "Home & Kitchen",
        brand: "HydroLife",
        stock: 120,
        featured: true,
        images: [{ public_id: "h1", url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400" }],
        tags: ["bottle", "insulated", "hydration"],
    },
    {
        name: "Non-Stick Cookware Set 5-Piece",
        description: "5-piece non-stick cookware set with PFOA-free coating, induction compatible.",
        price: 2499,
        originalPrice: 3999,
        category: "Home & Kitchen",
        brand: "KitchenPro",
        stock: 35,
        featured: true,
        images: [{ public_id: "h2", url: "https://images.unsplash.com/photo-1584990347449-39ce2c98d564?w=400" }],
        tags: ["cookware", "nonstick", "kitchen"],
    },
    {
        name: "Electric Kettle 1.5L",
        description: "1500W fast boil electric kettle with auto shut-off and boil dry protection.",
        price: 799,
        originalPrice: 1299,
        category: "Home & Kitchen",
        brand: "BrewFast",
        stock: 80,
        featured: false,
        images: [{ public_id: "h3", url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400" }],
        tags: ["kettle", "electric", "kitchen"],
    },
    {
        name: "Air Tight Container Set 6pcs",
        description: "Set of 6 airtight food storage containers in BPA-free plastic. Stackable design.",
        price: 599,
        originalPrice: 999,
        category: "Home & Kitchen",
        brand: "FreshKeep",
        stock: 90,
        featured: false,
        images: [{ public_id: "h4", url: "https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=400" }],
        tags: ["container", "storage", "kitchen"],
    },
    {
        name: "Bamboo Cutting Board Set",
        description: "Set of 3 organic bamboo cutting boards. Eco-friendly, easy to clean and knife-friendly.",
        price: 499,
        originalPrice: 899,
        category: "Home & Kitchen",
        brand: "EcoHome",
        stock: 65,
        featured: false,
        images: [{ public_id: "h5", url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400" }],
        tags: ["cutting board", "bamboo", "kitchen"],
    },
    {
        name: "Coffee Maker Drip Machine",
        description: "12-cup programmable drip coffee maker with thermal carafe and auto brew timer.",
        price: 3499,
        originalPrice: 5499,
        category: "Home & Kitchen",
        brand: "BrewFast",
        stock: 25,
        featured: true,
        images: [{ public_id: "h6", url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400" }],
        tags: ["coffee", "maker", "kitchen"],
    },
    {
        name: "Memory Foam Pillow",
        description: "Orthopedic memory foam pillow with cooling gel layer and washable bamboo cover.",
        price: 999,
        originalPrice: 1799,
        category: "Home & Kitchen",
        brand: "SleepWell",
        stock: 55,
        featured: false,
        images: [{ public_id: "h7", url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400" }],
        tags: ["pillow", "memory foam", "sleep"],
    },
    {
        name: "Digital Kitchen Scale",
        description: "Precision digital scale with 0.1g accuracy, 5kg capacity and LCD display.",
        price: 449,
        originalPrice: 799,
        category: "Home & Kitchen",
        brand: "KitchenPro",
        stock: 75,
        featured: false,
        images: [{ public_id: "h8", url: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=400" }],
        tags: ["scale", "kitchen", "baking"],
    },

    // Sports
    {
        name: "Yoga Mat Anti-Slip 6mm",
        description: "6mm thick eco-friendly yoga mat with alignment lines and carrying strap.",
        price: 899,
        originalPrice: 1499,
        category: "Sports",
        brand: "FlexFit",
        stock: 60,
        featured: false,
        images: [{ public_id: "s1", url: "https://images.unsplash.com/photo-1601925228604-75f9e0f9572c?w=400" }],
        tags: ["yoga", "mat", "fitness"],
    },
    {
        name: "Adjustable Dumbbell Set 20kg",
        description: "Adjustable dumbbell set from 2kg to 20kg with quick-change mechanism.",
        price: 4999,
        originalPrice: 7999,
        category: "Sports",
        brand: "IronFit",
        stock: 20,
        featured: true,
        images: [{ public_id: "s2", url: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400" }],
        tags: ["dumbbell", "weights", "gym"],
    },
    {
        name: "Resistance Bands Set 5pcs",
        description: "Set of 5 resistance bands (10-50lbs) with handles, ankle straps and door anchor.",
        price: 599,
        originalPrice: 999,
        category: "Sports",
        brand: "FlexFit",
        stock: 85,
        featured: false,
        images: [{ public_id: "s3", url: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400" }],
        tags: ["resistance bands", "workout", "fitness"],
    },
    {
        name: "Badminton Racket Set",
        description: "Premium carbon fiber badminton racket set with 2 rackets, 3 shuttlecocks and bag.",
        price: 1299,
        originalPrice: 2199,
        category: "Sports",
        brand: "SportsPro",
        stock: 40,
        featured: false,
        images: [{ public_id: "s4", url: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400" }],
        tags: ["badminton", "racket", "sports"],
    },
    {
        name: "Skipping Rope Speed",
        description: "Professional speed skipping rope with ball bearings and adjustable cable.",
        price: 299,
        originalPrice: 499,
        category: "Sports",
        brand: "FlexFit",
        stock: 120,
        featured: false,
        images: [{ public_id: "s5", url: "https://images.unsplash.com/photo-1600881333168-2ef49b341f30?w=400" }],
        tags: ["skipping", "cardio", "fitness"],
    },
    {
        name: "Gym Gloves with Wrist Support",
        description: "Padded gym gloves with integrated wrist wraps, anti-slip palm and breathable mesh.",
        price: 399,
        originalPrice: 699,
        category: "Sports",
        brand: "IronFit",
        stock: 95,
        featured: false,
        images: [{ public_id: "s6", url: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400" }],
        tags: ["gloves", "gym", "training"],
    },
    {
        name: "Sports Water Bottle 1L",
        description: "BPA-free sports bottle with straw lid, leak-proof and dishwasher safe.",
        price: 349,
        originalPrice: 599,
        category: "Sports",
        brand: "HydroLife",
        stock: 140,
        featured: false,
        images: [{ public_id: "s7", url: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400" }],
        tags: ["bottle", "sports", "hydration"],
    },

    // Beauty
    {
        name: "Face Moisturizer SPF 50",
        description: "Lightweight daily moisturizer with SPF 50, hyaluronic acid and vitamin C.",
        price: 449,
        originalPrice: 799,
        category: "Beauty",
        brand: "GlowUp",
        stock: 90,
        featured: false,
        images: [{ public_id: "be1", url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400" }],
        tags: ["moisturizer", "spf", "skincare"],
    },
    {
        name: "Vitamin C Serum 30ml",
        description: "20% vitamin C serum with ferulic acid. Brightens skin and reduces dark spots.",
        price: 599,
        originalPrice: 999,
        category: "Beauty",
        brand: "GlowUp",
        stock: 70,
        featured: true,
        images: [{ public_id: "be2", url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400" }],
        tags: ["serum", "vitamin c", "brightening"],
    },
    {
        name: "Hair Dryer 2000W Ionic",
        description: "Professional ionic hair dryer with 3 heat settings and cool shot button.",
        price: 1299,
        originalPrice: 2199,
        category: "Beauty",
        brand: "StylePro",
        stock: 45,
        featured: false,
        images: [{ public_id: "be3", url: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400" }],
        tags: ["hair dryer", "ionic", "styling"],
    },
    {
        name: "Electric Face Cleanser",
        description: "Sonic vibration electric face cleanser with silicone brush head and waterproof design.",
        price: 799,
        originalPrice: 1499,
        category: "Beauty",
        brand: "GlowUp",
        stock: 55,
        featured: false,
        images: [{ public_id: "be4", url: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400" }],
        tags: ["cleanser", "electric", "skincare"],
    },
    {
        name: "Perfume Floral Essence 100ml",
        description: "Long-lasting floral fragrance with top notes of rose and jasmine.",
        price: 1499,
        originalPrice: 2499,
        category: "Beauty",
        brand: "FragranceX",
        stock: 30,
        featured: false,
        images: [{ public_id: "be5", url: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=400" }],
        tags: ["perfume", "fragrance", "floral"],
    },

    // Toys
    {
        name: "LEGO Classic Brick Set 500pcs",
        description: "Classic LEGO brick set with 500 pieces in 35 colors for kids aged 4+.",
        price: 1999,
        originalPrice: 2999,
        category: "Toys",
        brand: "LEGO",
        stock: 40,
        featured: true,
        images: [{ public_id: "t1", url: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400" }],
        tags: ["lego", "building", "creative"],
    },
    {
        name: "Remote Control Car Off-Road",
        description: "4WD off-road RC car with 30km/h speed and rechargeable battery.",
        price: 1299,
        originalPrice: 2199,
        category: "Toys",
        brand: "SpeedRC",
        stock: 35,
        featured: false,
        images: [{ public_id: "t2", url: "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=400" }],
        tags: ["rc car", "remote control", "kids"],
    },
    {
        name: "Rubik's Cube Speed 3x3",
        description: "Professional speed cube with corner cutting and smooth rotation.",
        price: 299,
        originalPrice: 499,
        category: "Toys",
        brand: "CubePro",
        stock: 100,
        featured: false,
        images: [{ public_id: "t3", url: "https://images.unsplash.com/photo-1591991731833-b4807cf7ef48?w=400" }],
        tags: ["rubiks cube", "puzzle", "brain"],
    },
    {
        name: "Board Game Chess Set",
        description: "Premium wooden chess set with weighted pieces and folding board.",
        price: 899,
        originalPrice: 1499,
        category: "Toys",
        brand: "GameMaster",
        stock: 50,
        featured: false,
        images: [{ public_id: "t4", url: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=400" }],
        tags: ["chess", "board game", "strategy"],
    },

    // Other
    {
        name: "Leather Wallet Slim RFID",
        description: "Slim genuine leather wallet with RFID blocking, 6 card slots and bill compartment.",
        price: 699,
        originalPrice: 1199,
        category: "Other",
        brand: "LeatherCraft",
        stock: 80,
        featured: false,
        images: [{ public_id: "o1", url: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400" }],
        tags: ["wallet", "leather", "rfid"],
    },
    {
        name: "Scented Candle Set 3pcs",
        description: "Set of 3 hand-poured soy wax candles in lavender, vanilla and sandalwood. 45hr burn each.",
        price: 799,
        originalPrice: 1299,
        category: "Other",
        brand: "AromaHome",
        stock: 60,
        featured: false,
        images: [{ public_id: "o2", url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400" }],
        tags: ["candle", "scented", "home decor"],
    },
    {
        name: "Planner Journal 2024",
        description: "Premium undated planner with weekly layout, habit tracker and goal setting pages.",
        price: 499,
        originalPrice: 799,
        category: "Other",
        brand: "PaperCo",
        stock: 70,
        featured: false,
        images: [{ public_id: "o3", url: "https://images.unsplash.com/photo-1517971071642-34a2d3eccb33?w=400" }],
        tags: ["planner", "journal", "productivity"],
    },
];

const seed = async() => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log("✅ Connected to MongoDB");

        await Product.deleteMany();
        await Product.insertMany(products);
        console.log(`✅ ${products.length} products seeded successfully!`);

        await User.deleteOne({ email: "admin@shopease.com" });
        await User.create({
            name: "Admin",
            email: "admin@shopease.com",
            password: "admin123",
            role: "admin",
        });
        console.log("✅ Admin created: admin@shopease.com / admin123");

        process.exit(0);
    } catch (err) {
        console.error("❌ Seeder error:", err.message);
        process.exit(1);
    }
};

seed();